blog/urls.py
from django.urls import path
from .views import (BlogListView, BlogCreateView, BlogDetailView, 
                    BlogUpdateView, BlogDeleteView)


'''archivo que se utiliza para definir las urls de la aplicacion.
Se importa la vista que se va a utilizar y 
se define la url que se va a utilizar para acceder a esta vista.'''

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='home'),
    
    path('create/', BlogCreateView.as_view(), name='create'),

    # indicamos que la url va a recibir un parametro que va a ser el id del post
    path('<int:pk>/', BlogDetailView.as_view(), name='detail'),

    # path('<int:pk>/update/', BlogUpdateView.as_view(), name='update'),    
    path('<int:pk>/update/', BlogUpdateView.as_view(), name='update'),

    path('<int:pk>/delete/', BlogDeleteView.as_view(), name= 'delete')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', HomeView.as_view(), name='home'),

    path('blog/', include('blog.urls', namespace='blog'))
]

blog/models.py
from django.db import models

""" archivo que se utiliza para crear tablas en la base de datos. 
Esto se hace creando clases que heredan de models.Model y 
definiendo los atributos dentro de esta. Cada atributo representa una columna
en la tabla de la base de datos.

Cada vez que se modifica este archivo, se debe correr el comando 
'python manage.py makemigrations' para que Django actualice la 
base de datos con los cambios."""

# Create your models here.
class Post(models.Model):
    # creamos un campo el la base de datos de tipo texto
    title=models.CharField(max_length=250)
    #el textfield es un campo de texto mas largo que el charfield
    content=models.TextField()

    '''Podemos modificar como se muestra el objeto en el panel del 
    administrador de Django sobreescribiendo el metodo __str__'''
    def __str__(self):
        return self.title

blog/forms.py
from django import forms

from .models import Post


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields=('title', 'content')

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, UpdateView, DeleteView
from .forms import PostCreateForm
from .models import Post
from django.urls import reverse_lazy

'''Este archivo se utiliza para definir las vistas de la aplicacion.
se creara una clase que hereda de View y se sebreescribira el metodo get
para que retorne la respuesta http, el nombre de la plantilla que se 
quiere mostrar y el contexto que se le quiere pasar a la plantilla'''

# Creamos una vista para la agina de los blogs
class BlogListView(View):
    def get(self, request, *args, **kwargs):

        # obtenemos los distintos post que hay en la base de datos
        posts = Post.objects.all()
        context = {
            # pasamos los post al contexto para mostrarlo luego en 
            # la plantilla html
            'posts':posts

        }

        return render(request, 'blog_list.html', context)
    
# creamos una nueva vista para crear post
class BlogCreateView(View):

    '''sobrescribimos el metodo get para que retorne el formulario
    que creamos en forms.py y lo pase como contexto a la plantilla
    para que se muestre en la pagina web.'''
    def get(self, request, *args, **kwargs):
        # referenciamos al formulario que creamos
        form=PostCreateForm()
        #creamos un contexto 
        context={
            'form':form
        }
        return render(request, 'blog_create.html', context)
    
    '''sobrescribimos el metodo post para que cuando se envie el
    formulario, se cree un nuevo objeto en la base de datos con los
    datos que se enviaron en el formulario.'''
    def post(self, request, *args,**kwargs):
        if request.method=='POST':
            # creamos un objeto del formulario con los datos que se enviaron
            form = PostCreateForm(request.POST)
            # comprobamos si el formulario es valido
            if form.is_valid():
                # obtenemos los datos del formulario que se enviaron
                title = form.cleaned_data.get('title')
                content = form.cleaned_data.get('content')

                # con los datos que se obtuvieron, creamos un nuevo objeto

                p, created = Post.objects.get_or_create(title=title, content=content)
                # guardamos el objeto en la base de datos
                p.save()
                # redirigimos a la pagina de inicio
                # pasamos al redirect el nombre de la url a la que queremos redirigir
                return redirect('blog:home')
        context={

        }
        return render(request, 'blog_create.html', context)

# creamos una vista para ver los detalles de un post
class BlogDetailView(View):

    def get(self, request, pk, *args, **kwargs):
        # obtenemos el post correspondiente al id (pk) proporcionado
        post = get_object_or_404(Post, pk=pk)
        context={
            # pasamos el post al contexto para mostrarlo en la plantilla html
            'post':post
        }
        # renderizamos la plantilla 'blog_detail.html' con el contexto proporcionado
        return render(request, 'blog_detail.html', context)
    
class BlogUpdateView(UpdateView):
    # indicamos en que modelo se va a hacer la actualizacion
    model = Post
    # indicamos que campos se van a actualizar
    fields =  [
        'title',
        'content',
    ]
    # indicamos el nombre de la plantilla que se va a utilizar
    template_name = 'blog_update.html'

    # indicamos el nombre de la url a la que se va a redirigir
    # una vez que se haya actualizado el post
    def get_success_url(self):
        # Obtenemos el valor de 'pk' de los argumentos de la vista
        pk = self.kwargs['pk']
        # Creamos la URL de redirección utilizando el valor de 'pk' en los argumentos de la vista
        return reverse_lazy('blog:detail', kwargs={'pk':pk})
    
class BlogDeleteView(DeleteView):
    model = Post

    # indicamos el nombre de la plantilla que se va a utilizar
    template_name = 'blog_delete.html'

    # indicamos la url a la que se va a redirigir una vez que se haya eliminado el post
    success_url = reverse_lazy('blog:home')

core/views.py
from django.views.generic import View
from django.shortcuts import render

class HomeView(View):
    def get(self, request, *args, **kwargs):
        context={

        }
        return render(request, 'index.html', context)

templates/base.html
{% load tailwind_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% tailwind_css %}

    <title>Document</title>
</head>
<body>
    
    {% block content %}{% endblock content %}

</body>
</html>

templates/blog_create.html
<!--En este código, se está mostrando el contenido de un formulario 
    en un archivo HTML utilizando la sintaxis de Django. La variable 
    form.content contiene el contenido ingresado por el usuario en el 
    formulario y se muestra en la página web. El texto "content" está 
    encerrado entre doble llaves '{ { } }', lo cual indica que es una 
    variable de Django que se renderizará en el HTML final.-->
<form method='POST'>
    {% csrf_token %}
    title{{form.title}}
    <br>
    content{{form.content}}
    <br>
    <!--El botón de tipo submit envía el formulario al servidor para
        ser procesado.-->
    <button type='submit'>Submit</button>
</form>

templates/blog_delete.html
<p> Are you sure you want to delete {{object}}?</p>
<form method='POST'>
    {% csrf_token %}
    {{form}}
    <button type='submit'>Delete</button>
</form>

templates/blog_detail.html
{{post.title}}
<br>
{{post.content}}

templates/blog_list.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <p>blog aqui</p>
        <br>
        {% for post in posts %}
        <a href="{% url 'blog:detail' post.id %}"> {{post.title}}</a>
        <a href="{% url 'blog:update' post.id %}"> Update</a>
        <a href="{% url 'blog:delete' post.id %}"> Delete</a>
        <br>
        {% endfor %}
        <br>
        <a href="{% url 'blog:create' %}"> Create</a>
        <script src="" async defer></script>
    </body>
</html>

templates/blog_update.html
<form method='POST'>
    {% csrf_token %}
    title{{form.title}}
    <br>
    content{{form.content}}
    <br>
    <!--El botón de tipo submit envía el formulario al servidor para
        ser procesado.-->
    <button type='submit'>Update</button>
</form>

templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Home</h1>
    <p>visita mi blog <a href="{% url 'blog:home' %}">aquí</a></p>
{% endblock content %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>